app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mixins.assets import Index

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("suppliers/", include("suppliers.urls", namespace="suppliers")),
    path("products/", include("products.urls", namespace="products")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("employees/", include("employees.urls", namespace="employees")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/deliveries/urls.py
from django.urls import path

from . import views

app_name = "deliveries"

urlpatterns = [
    path("", views.DeliveryListView.as_view(), name="delivery-list"),
    path("detail/<int:pk>", views.DeliveryDetailView.as_view(), name="delivery-detail"),
    path("update/<int:pk>", views.DeliveryUpdateView.as_view(), name="delivery-update"),
    path("create", views.DeliveryCreateView.as_view(), name="delivery-create"),
]

app/deliveries/models.py
import uuid
from django.db import models
from django.urls import reverse
from mixins.assets import TimeStampMixin
from products.models import Product

# def uid():
#     uid = uuid.uuid4()
#     uid = str(uid).upper()
#     return uid.split("-")[4]



# Create your models here.
class Delivery(TimeStampMixin):
    # uid = models.CharField(max_length=20, editable=False, default=uid())

    product = models.ForeignKey(
        Product, related_name="deliveries", on_delete=models.SET_NULL, null=True
    )
    qty = models.IntegerField(default=0)
    delivery_date = models.DateField(blank=True, null=True)
    deliveried_to = models.CharField(max_length=100, blank=True, null=True)
    deliveried_by = models.CharField(max_length=100, blank=True, null=True)
    delivery_comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Deliveries"

    def get_absolute_url(self):
        return reverse("deliveries:delivery-detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse("stores:deliveries-update", kwargs={"pk": self.pk})

    def get_delivered_quantity(self):
        return self.qty

    def __str__(self):
        return self.product.name

app/deliveries/forms.py
from django import forms

from .models import Delivery


class DeliveryCreateForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "delivery_date": forms.DateInput(attrs={"type": "date"}),
            "delivery_comment": forms.Textarea(attrs={"rows": 3}),
        }


class DeliveryUpdateForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "delivery_date": forms.DateInput(attrs={"type": "date"}),
            "delivery_comment": forms.Textarea(attrs={"rows": 3}),
        }

app/deliveries/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from .models import Delivery
from .forms import DeliveryCreateForm, DeliveryUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


class DeliveryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Delivery
    form_class = DeliveryCreateForm
    success_message = "%(product)s was created successfully"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class DeliveryUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Delivery
    form_class = DeliveryUpdateForm
    success_message = "%(product)s was updated successfully"
    template_name_suffix = '_update_form'

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class DeliveryDetailView(LoginRequiredMixin, DetailView):
    model = Delivery
    context_object_name = "delivery"



class DeliveryListView(LoginRequiredMixin, ListView):
    model = Delivery
    context_object_name = "deliveries"

app/templates/deliveries/delivery_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{delivery|title}}
{% endblock head_title %}



{% block content %}
<div class="container my-5">
    <h1 class="fs-1">{{delivery|title}}</h1>
    <hr>
  
    <div class="card mx-auto mt-5 col-sm-12 col-md-12 col-lg-6"
        ">
        <div class="card-header">
            <h5 class="card-title">Details</h5>
        </div>
        <div class="card-body">
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{delivery.uid}}</p>
                <span class="card-text text-muted small">UID</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{delivery.product.supplier|title}}</p>
                <span class="card-text text-muted small">supplier</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{delivery.qty|default:"---"}}</p>
                <span class="card-text text-muted small">delivered</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{delivery.delivery_date|default:"---"}}</p>
                <span class="card-text text-muted small">delivery_date </span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{delivery.received_comment|default:"---"}}</p>
                <span class="card-text text-muted small">delivery_comment</span>

            </div>
        
        </div>
        <div class="card-footer">
            <a class="btn btn-dark px-5" href="{{order.get_update_url}}">Edit</a>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/deliveries/delivery_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}

New Delivery

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">New Delivery</h1>
    <hr>
    <div class="card mx-auto col-sm-12 col-md-12 col-lg-6 small mt-5">
        <h5 class="card-header">New Delivery</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

app/templates/deliveries/delivery_list.html
{% extends 'base.html' %}


{% block head_title %}
Deliveries
{% endblock head_title %}


{% block content %}
<div class="container my-5">
        <h1 class="fs-1 list-inline-item ">Deliveries</h1>
        <hr>
            <a href="{% url 'deliveries:delivery-create' %}"
                class="btn btn-dark px-5 text-end">add</a>
                <div class="my-5">
    {% for delivery in deliveries %}
    <a href="{{delivery.get_absolute_url }}">
        {{delivery|title}}
    </a>
    <hr>
    {% empty %}
    <p class="text-center">No Deliveries</p>
    {% endfor %}
</div>
</div>
{% endblock content %}

app/templates/deliveries/order_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}

{{order|title}}

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">{{object|title}}</h1>
    <hr>
    <div class="card mx-auto col-sm-12 col-md-12 col-lg-6 small mt-5">
        <h5 class="card-header">Update {{order}}</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}