app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mixins.assets import Index

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("suppliers/", include("suppliers.urls", namespace="suppliers")),
    path("products/", include("products.urls", namespace="products")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("employees/", include("employees.urls", namespace="employees")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/suppliers/urls.py
from django.urls import path

from . import views

app_name = "suppliers"

urlpatterns = [
    path("", views.SupplierListView.as_view(), name="supplier-list"),
    path("search/", views.SupplierSearch.as_view(), name="supplier-search"),
    path(
        "detail/<slug:slug>", views.SupplierDetailView.as_view(), name="supplier-detail"
    ),
    path("create", views.SupplierCreateView.as_view(), name="supplier-create"),
    path(
        "update/<slug:slug>", views.SupplierUpdateView.as_view(), name="supplier-update"
    ),
    path(
        "delete/<slug:slug>", views.SupplierDeleteView.as_view(), name="supplier-delete"
    ),
]

app/suppliers/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from mixins.assets import DISTRICT_LIST, TimeStampMixin

# create a model manager filter
class IsNotDeletedManager(models.Manager):
    def get_queryset(self):
        return super(IsNotDeletedManager, self).get_queryset().filter(is_deleted=False)


# class Tag(TimeStampMixin):
#     name = models.CharField(max_length=100, blank=True, null=True)

#     class Meta:
#         ordering = ["name"]

#     def __str__(self):
#         return self.name


class Supplier(TimeStampMixin):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    district = models.CharField(
        max_length=25, choices=DISTRICT_LIST, default="Castries"
    )
    website = models.URLField(blank=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    tags = models.TextField(
        blank=True, null=True, help_text="Tags separated by comma eg.: #tag, #tags"
    )

    objects = models.Manager()
    object_list = IsNotDeletedManager()

    class Meta:
        ordering = ["name"]

    def get_delete_url(self):
        return reverse("suppliers:supplier-delete", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("suppliers:supplier-update", kwargs={"slug": self.slug})

    def get_absolute_url(self):
        return reverse("suppliers:supplier-detail", kwargs={"slug": self.slug})

    def get_full_address(self):
        return "%s, %s" % (self.address, self.district)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Supplier, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

app/suppliers/forms.py
from django import forms

from .models import Supplier


class SupplierDeleteForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ["is_deleted"]


class SupplierCreateForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = "__all__"
        exclude = ["created_by", "updated_by", "slug", "is_deleted"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
            "tags": forms.Textarea(attrs={"rows": 3}),
        }


class SupplierUpdateForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = "__all__"
        exclude = ["created_by", "updated_by", "slug", "is_deleted"]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}

app/suppliers/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    TemplateView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy

from .models import Supplier
from .forms import SupplierCreateForm, SupplierUpdateForm, SupplierDeleteForm
from products.models import Product
from employees.models import Employee


class SupplierSearch(LoginRequiredMixin, ListView):
    model = Supplier
    template_name = "suppliers/supplier_search.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("q")
        if query:
            suppliers = Supplier.object_list.filter(
                Q(name__icontains=query)
                | Q(tags__icontains=query)
                | Q(description__icontains=query)
                | Q(email__icontains=query)
                | Q(phone__icontains=query)
                | Q(address__icontains=query)
                | Q(district__icontains=query)
            ).distinct()
            context["suppliers"] = suppliers
        else:
            context["suppliers"] = Supplier.objects.all()
        return context


class SupplierListView(LoginRequiredMixin, SuccessMessageMixin, FormMixin, ListView):
    model = Supplier
    form_class = SupplierCreateForm
    queryset = Supplier.object_list.all()
    context_object_name = "suppliers"
    paginate_by = 10
    success_message = "%(name)s was created successfully"


class SupplierDetailView(LoginRequiredMixin, DetailView):
    model = Supplier
    context_object_name = "supplier"


class SupplierCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Supplier
    form_class = SupplierCreateForm
    success_message = "%(name)s was created successfully"
    success_url = reverse_lazy("suppliers:supplier-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated = self.request.user
        return super().form_valid(form)


class SupplierUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Supplier
    form_class = SupplierUpdateForm
    template_name_suffix = "_update_form"
    success_message = "%(name)s was updated successfully"

    def form_valid(self, form):
        form.instance.updated = self.request.user
        return super().form_valid(form)


class SupplierDeleteView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Supplier
    form_class = SupplierDeleteForm
    success_message = "Delete successfully"
    success_url = reverse_lazy("suppliers:supplier-list")

    def form_valid(self, form):
        form.instance.updated = self.request.user
        form.instance.is_deleted = True
        return super().form_valid(form)

app/templates/suppliers/supplier_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{supplier|title}}
{% endblock head_title %}



{% block content %}
<div class="container my-5">
    <div class="my-5">
        <a class="btn btn-outline-dark px-5"
            href="{% url 'suppliers:supplier-list' %}">Back to list</a>
    </div>
    <h1 class="fs-1">{{supplier|title}}</h1>
    <hr>

    <div class="card mx-auto mt-5 col-sm-12 col-md-12 col-lg-6 shadow" ">
        <div class="
        card-header">
        <h5 class="card-title">Details</h5>
    </div>
    <div class="card-body">
        <div class="mb-2">
            <p class="card-text my-0 border-bottom">
                <a class="text-decoration-none text-dark"
                    href="mailto:{{supplier.email}}">
                    {{supplier.email}}
                </a>
            </p>
            <span class="card-text text-muted small">email</span>

        </div>
        <div class="mb-2">
            <p class="card-text my-0 border-bottom">
                <a class="text-decoration-none text-dark"
                    href="tel:{{supplier.phone}}">
                    {{supplier.phone}}
                </a>
            </p>
            <span class="card-text text-muted small">phone</span>

        </div>
        <div class="mb-2">
            <p class="card-text my-0 border-bottom">
                {{supplier.get_full_address|title}}</p>
            <span class="card-text text-muted small">address</span>

        </div>
        <div class="mb-2">
            <p class="card-text my-0 border-bottom">
                <a target="_blank"
                    href="{{supplier.website}}">
                    {{supplier.website}}
                </a>
            </p>
            <span class="card-text text-muted small">website</span>

        </div>
        <div class="mb-2">
            <p class="card-text my-0 border-bottom">
                {{supplier.is_active|yesno:"yes,no"|title}}</p>
            <span class="card-text text-muted small">is active</span>

        </div>
    </div>
    <div class="card-footer text-end">
        <div class="d-grid gap-2 d-md-block">

           
            <form action="{{supplier.get_delete_url}}"
                method="POST">
                {% csrf_token %}

                <button class="btn btn-sm btn-outline-danger"
                    type="submit">Delete</button>
                    <a class="btn btn-outline-dark px-5"
                    href="{{supplier.get_update_url}}">Edit</a>
        </div>

            </form>

    </div>
</div>
</div>
{% endblock content %}

app/templates/suppliers/supplier_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block head_title %}
Suppliers
{% endblock head_title %}


{% block content %}

<div class="row">
    <!-- card 1 -->
    <div class="card mx-auto px-0"
        style="max-width: 60%">
        <h5 class="card-header text-center">Suppliers</h5>

        <form class="m-5"
            action="{% url 'suppliers:supplier-search' %}"
            method="get">
            <input class="form-control form-control-sm rounded-pill"
                type="text"
                name="q"
                placeholder="search suppliers by (name, description, email, phone, address, district)..."
                aria-label="Search">
        </form>
        <div class="card-body">
            {% include 'pagination.html' %}
            <div class="table-responsive">
                <table class="table table-hover small">
                    <thead>
                        <tr>
                            <th scope="col">suppliers</th>
                            <th scope="col">phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supplier in suppliers %}
                        <tr>
                            <td>
                                <a title="product details"
                                    class="text-decoration-none text-dark"
                                    href="{{supplier.get_absolute_url }}">
                                    {{supplier.name}}
                                </a>
                            <td title="phone">
                                <a href="tel:{{supplier.phone|default:'--'}}">
                                    {{supplier.phone|default:'--'}}
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="text-center"
                                colspan="2">
                                No Suppliers
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include 'pagination.html' %}

        </div>
    </div>
    <!-- card 1 -->


    <!-- card 2 -->

    <div class="mx-auto px-0"
        style="max-width: 30%;">
        <!-- Button trigger modal -->
        <button type="button"
            class="btn btn-lg btn-dark"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal">
            Add Supplier
        </button>
    </div>

    <!-- <div class="card mx-auto px-0"
            style="max-width: 30%;">
            <h5 class="card-header text-center">Add</h5>

            <div class="card-body">
                <form action="{% url 'suppliers:supplier-create' %}"
                    method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-dark px-5 my-3"
                        type="submit">submit</button>
                </form>
            </div>
        </div> -->
    <!-- card 2 -->

</div>




<!-- Modal -->
<div class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="exampleModalLabel">Supplier Details</h5>
                <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="p-5"
                    action="{% url 'suppliers:supplier-create' %}"
                    method="post">
                    {% csrf_token %}
                    {{form|crispy}}

            </div>
            <div class="modal-footer">
                <button type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal">Close</button>
                <button class="btn btn-dark px-5 my-3"
                    type="submit">submit</button>

                </form>

            </div>
        </div>
    </div>
</div>



{% endblock content %}

app/templates/suppliers/supplier_search.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block head_title %}
Suppliers
{% endblock head_title %}


{% block content %}
<div class="container my-5">
    <form class="
    action="
        {%
        url 'suppliers:supplier-search'
        %}">
        <input class="form-control rounded-pill"
            type="text"
            name="q"
            placeholder="search suppliers by (name, description, email, phone, address, district)..."
            aria-label="Search">
    </form>

    <div class="my-5">
        {% for supplier in suppliers %}
        <h2>
            <a href="{{supplier.get_absolute_url }}">
                {{supplier.name}}
            </a>
        </h2>

        <div class="container">
            <span class="text-muted">
                {{supplier.address}} {{supplier.district}}
            </span>
                {{supplier.description}}
            <span>
                <a class="text-decoration-none fw-bolder text-muted" href="mailto:{{supplier.email|default:''}}">
                    {{supplier.email}}
                </a>
            </span>
            <span>
                <a class="text-decoration-none fw-bolder text-muted" href="tel:{{supplier.phone|default:""}}">
                    {{supplier.phone}}
                </a>
            </span>
            <span>
                <a target="_blank" class="text-decoration-none fw-bolder text-muted" href="{{supplier.website|default:""}}">
                    {{supplier.website}}
                </a>
            </span>
        </div>
    </div>
    {% empty %}
    <p class="text-center">We weren't able to find anything...</p>
    {% endfor %}



</div>
{% endblock content %}


<div class="container my-5">

</div>
<div class="container my-5">

    <h1 class="fs-1 text-center">Results</h1>
    <hr>

    <div class="my-5">

        <div class="my-5">
            {% include 'pagination.html' %}
            <div class="table-responsive">
                <table class="table table-hover small">
                    <thead>
                        <tr>
                            <th scope="col">supplier</th>
                            <th scope="col">phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supplier in suppliers %}
                        <tr>
                            <td>
                                <a title="product details"
                                    class="text-decoration-none text-dark"
                                    href="{{supplier.get_absolute_url }}">
                                    {{supplier.name}}
                                </a>
                                <!-- </td>
                                        <td title="email">
                                            <a
                                                href="mailto:{{supplier.email|default:'--'}}">
                                                {{supplier.email}}
                                            </a>
                                        </td> -->
                            <td title="phone">
                                <a href="tel:{{supplier.phone|default:'--'}}">
                                    {{supplier.phone}}
                                </a>
                            </td>
                            <!-- <td title="website">
                                            <a target="_blank"
                                                href="{{supplier.email|default:'--'}}">
                                                {{supplier.website}}
                                            </a>
                                        </td> -->
                        </tr>
                        </a>
                        {% empty %}
                        <td colspan="4"
                            class="text-center">No Suppliers
                            <td />
                            {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include 'pagination.html' %}

        </div>

    </div>
</div>