app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mixins.assets import Index

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("suppliers/", include("suppliers.urls", namespace="suppliers")),
    path("products/", include("products.urls", namespace="products")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("employees/", include("employees.urls", namespace="employees")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product-list"),
    path("search/", views.ProductSearchListView.as_view(), name="product-search"),
    path("detail/<slug:slug>", views.ProductDetailView.as_view(), name="product-detail"),
    path("create", views.ProductCreateView.as_view(), name="product-create"),
    path("update/<slug:slug>", views.ProductUpdateView.as_view(), name="product-update"),
]

app/products/models.py
from django.db import models
from mixins.assets import TimeStampMixin
from django.urls import reverse
from django.utils.text import slugify
from suppliers.models import Supplier


class Category(TimeStampMixin):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(TimeStampMixin):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.SET_NULL, null=True
    )
    supplier = models.ForeignKey(
        Supplier, related_name="product_suppliers", on_delete=models.SET_NULL, null=True
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    tags = models.TextField(
        blank=True, null=True, help_text="Tags separated by comma eg.: #tag, #tags"
    )
    image = models.ImageField(upload_to="products/", blank=True)
    description = models.TextField(blank=True)
    init_qty = models.IntegerField("initial quantity", default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("products:product-update", kwargs={"slug": self.slug})

    def get_order_balance(self):
        return sum(
            (order.get_order_quantity() for order in self.orders.all()), self.init_qty
        )
        # ) - (sum(item.get_delivered_quantity() for item in self.delivered_goods.all()))

    def get_delivered_balance(self):
        return sum(
            delivery.get_delivered_quantity() for delivery in self.deliveries.all()
        )

    def get_inventory_balance(self):
        return self.get_order_balance() - self.get_delivered_balance()

    def __str__(self):
        return self.name

app/products/forms.py
from django import forms

from .models import Product


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ["slug", "updated_by", "created_by"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
            "tags": forms.Textarea(attrs={"rows": 3}),
        }


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ["slug", "updated_by", "created_by"]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}

app/products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product
from .forms import ProductCreateForm, ProductUpdateForm
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q


class ProductSearchListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "products/product_search.html"
    context_object_name = "products"
    paginate_by = 10
    queryset = Product.objects.all()

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Product.objects.filter(
                Q(category_name__icontains=query)
                | Q(supplier_name__icontains=query)
                | Q(name__icontains=query)
                | Q(tags__icontains=query)
                | Q(description__icontains=query)
            )
        else:
            return Product.objects.all()


class ProductListView(LoginRequiredMixin, FormMixin, ListView):
    model = Product
    form_class = ProductCreateForm
    context_object_name = "products"
    paginate_by = 10
    


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = "product"


class ProductCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    success_message = "%(name)s was created successfully"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name_suffix = "_update_form"
    success_message = "%(name)s was updated successfully"

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)

app/templates/products/product_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}

New Product

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">New Product</h1>
    <hr>
    <div class="card mx-auto col-sm-12 col-md-12 col-lg-6 small mt-5">
        <h5 class="card-header">New Product</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

app/templates/products/product_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{product}}
{% endblock head_title %}



{% block content %}
<div class="container my-5">
    <div class="my-5">
        <a class="btn btn-outline-dark px-5" href="{% url 'products:product-list' %}">Back to list</a>
    </div>
    <h1 class="fs-1">{{product}}</h1>
    <hr>
  
    <div class="card mx-auto mt-5 col-sm-12 col-md-12 col-lg-6"
        ">
        <div class="card-header">
            <h5 class="card-title">Details</h5>
        </div>
        <div class="card-body">
         
         
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{product.supplier|title}}</p>
                <span class="card-text text-muted small">supplier</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{product.get_inventory_balance|default:"---"}}</p>
                <span class="card-text text-muted small">init_qty</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{product.description|default:"---"}}</p>
                <span class="card-text text-muted small">description</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">{{product.category|title}}</p>
                <span class="card-text text-muted small">category</span>

            </div>
            <div class="mb-2">
                <p class="card-text my-0 border-bottom">
                    <a class="text-decoration-none text-dark"
                    {% if product.image %}
                    target="_blank" 
                    href="{{product.image.url|default:'#'}}"
                    {% else %}
                    href=""
                    {% endif %}
                         >
                    {{product.image|default:"---"}}
                </a>
                </p>
                <div class="text-center">
                <span class="card-text text-muted small">image</span>
            </div>

            </div>
       
        </div>
        <div class="card-footer">
            <a class="btn btn-dark px-5" href="{{product.get_update_url}}">Edit</a>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/products/product_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}

New Product

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">New Product</h1>
    <hr>
    <div class="card mx-auto small mt-5 shadow-lg p-5" style="width: 40%;">
        <h5 class="card-header">New Product</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">Save</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

app/templates/products/product_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block head_title %}
Products
{% endblock head_title %}


{% block content %}

<div class="container my-5">
    <h1 class="fs-1 list-inline-item ">Products</h1>
    <hr>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-dark px-5" data-bs-toggle="modal" data-bs-target="#exampleModal">
    New
  </button>
   
    <div class="my-5">
        {% include 'pagination.html' %}
        <div class="table-responsive">
            <table class="table table-hover small">
                <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>
                            <a title="product details" class="text-decoration-none text-dark" href="{{product.get_absolute_url }}">
                                {{product.name}}
                            </a>
                        </td>
                        <td title="balance">
                            {{product.get_inventory_balance}}
                        </td>
                    </tr>
                    </a>
                    {% empty %}
                    <p class="text-center">No Products</p>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include 'pagination.html' %}

    </div>
</div>


  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body small">
         <form class="p-5" action="{% url 'products:product-create' %}" method="post">
           {% csrf_token %}
             {{form|crispy}}
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-dark px-5" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-dark px-5">Save</button>
        </form>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/products/product_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{{object}}
{% block head_title %}

{{object}}

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">{{object|title}}</h1>
    <hr>
    <div class="card mx-auto col-sm-12 col-md-12 col-lg-6 small mt-5">
        <h5 class="card-header">Update</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

app/templates/products/supplier_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{{object|title}}
{% block head_title %}

{{object|title}}

{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1 class="fs-1">{{object|title}}</h1>
    <hr>
    <div class="card mx-auto col-sm-12 col-md-12 col-lg-6 small mt-5">
        <h5 class="card-header">Update</h5>
        <div class="card-body">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit"
                    class="btn btn-dark my-3 px-5">submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}