app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mixins.assets import Index

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("suppliers/", include("suppliers.urls", namespace="suppliers")),
    path("products/", include("products.urls", namespace="products")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("employees/", include("employees.urls", namespace="employees")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/employees/urls.py
from django.urls import path

from . import views

app_name = "employees"

urlpatterns = [
    path("", views.EmployeeListView.as_view(), name="employee-list"),
    path("detail/<int:pk>", views.EmployeeDetailView.as_view(), name="employee-detail"),
    path("update/<int:pk>", views.EmployeeUpdateView.as_view(), name="employee-update"),
]

app/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("", views.OrderListView.as_view(), name="order-list"),
    path("detail/<int:pk>", views.OrderDetailView.as_view(), name="order-detail"),
    path("update/<int:pk>", views.OrderUpdateView.as_view(), name="order-update"),
    path("create", views.OrderCreateView.as_view(), name="order-create"),
]

app/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product-list"),
    path("search/", views.ProductSearchListView.as_view(), name="product-search"),
    path("detail/<slug:slug>", views.ProductDetailView.as_view(), name="product-detail"),
    path("create", views.ProductCreateView.as_view(), name="product-create"),
    path("update/<slug:slug>", views.ProductUpdateView.as_view(), name="product-update"),
]

app/suppliers/urls.py
from django.urls import path

from . import views

app_name = "suppliers"

urlpatterns = [
    path("", views.SupplierListView.as_view(), name="supplier-list"),
    path("search/", views.SupplierSearch.as_view(), name="supplier-search"),
    path(
        "detail/<slug:slug>", views.SupplierDetailView.as_view(), name="supplier-detail"
    ),
    path("create", views.SupplierCreateView.as_view(), name="supplier-create"),
    path(
        "update/<slug:slug>", views.SupplierUpdateView.as_view(), name="supplier-update"
    ),
    path(
        "delete/<slug:slug>", views.SupplierDeleteView.as_view(), name="supplier-delete"
    ),
]

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">

    <link rel="stylesheet"
        href="{% static 'css/main.css' %}">

    <link rel="stylesheet"
        href="{% static 'css/sidebar.css' %}">

    <title>
        {% block head_title %}

        {% endblock %}
        - Accountant General's Department
    </title>
</head>

<body>
    {% include 'message.html' %}
    <div class="row">
        <div class="col-lg-2">
            {% include 'sidebar.html' %}
        </div>
        <div class="col mt-5">
            {% block content %}

            {% endblock content %}
        </div>
    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>





    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

    <script>
        $(".form-control").addClass("form-control-sm");
        $(".btn").addClass("btn-sm");
    </script>
</body>

</html>

app/templates/header.html
<header class="p-3 mb-3 border-bottom bg-success">
        <div class="container">
                <div
                        class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                        <ul
                                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                                <!-- <li><a href="#"
                                                class="nav-link px-2 link-dark dropdown-toggle text-light"
                                                href="#"
                                                id="navbarDarkDropdownMenuLink"
                                                role="button"
                                                data-bs-toggle="dropdown"
                                                aria-expanded="false">Inventory</a>
                                        <ul class="dropdown-menu"
                                                aria-labelledby="navbarDarkDropdownMenuLink">
                                                <li><a class="dropdown-item"
                                                                href="#">Action</a>
                                                </li>
                                                <li><a class="dropdown-item"
                                                                href="#">Another
                                                                action</a></li>
                                                <li><a class="dropdown-item"
                                                                href="#">Something
                                                                else here</a>
                                                </li>
                                        </ul>
                                </li> -->
                                <li>
                                        <a href="{% url 'products:product-list' %}"
                                                class="nav-link px-2 link-dark text-light">Products</a>
                                </li>



                                <li><a href="{% url 'suppliers:supplier-list' %}"
                                                class="nav-link px-2 link-dark text-light">Suppliers</a>
                                </li>
                                <li><a href="{% url 'orders:order-list' %}"
                                                class="nav-link px-2 link-dark text-light">Orders</a>
                                </li>
                                <li><a href="{% url 'deliveries:delivery-list' %}"
                                                class="nav-link px-2 link-dark text-light">Deliveries</a>
                                </li>
                                {% if user.employee.is_ag %}
                                <li><a href="#"
                                                class="nav-link px-2 link-dark text-light"
                                                href="#"
                                                id="navbarDarkDropdownMenuLink"
                                                role="button"
                                                data-bs-toggle="dropdown"
                                                aria-expanded="false">Employees</a>
                                        <ul class="dropdown-menu"
                                                aria-labelledby="navbarDarkDropdownMenuLink">
                                </li>
                                <li><a class="dropdown-item"
                                                href="{% url 'employees:employee-list' %}">Employee
                                                List
                                        </a></li>
                                <li><a class="dropdown-item"
                                                href="#">Something
                                                else here</a>
                                </li>
                        </ul>
                        </li>
                        {% endif %}
                        </ul>

                       


                        {% if user.is_authenticated %}
                        <div class="dropdown text-end">
                                <a href="#"
                                        class="d-block link-dark text-decoration-none text-light"
                                        id="dropdownUser1"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <button style="height: 3rem; width:3rem;"
                                                class="btn btn-dark rounded-circle">{{user.employee.get_employee_initials}}</button>
                                </a>
                                <ul class="dropdown-menu text-small"
                                        aria-labelledby="dropdownUser1">

                                        <li><a class="dropdown-item"
                                                        href="{{ user.employee.get_absolute_url }}">Profile
                                                </a>
                                        </li>
                                        <li><a class="dropdown-item"
                                                        href="{% url 'account_email' %}">Change
                                                        E-mail</a>
                                        </li>
                                        <li>
                                                <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item"
                                                        href="{% url 'account_logout' %}">Sign
                                                        out</a></li>
                                </ul>
                        </div>
                        {% endif %}
                </div>
        </div>
</header>
<header class="py-3 mb-4 border-bottom">
        <div class="container d-flex flex-wrap justify-content-center">
                <a href="/"
                        class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
                        <svg class="bi me-2"
                                width="40"
                                height="32">
                                <use xlink:href="#bootstrap" />
                        </svg>
                        <span class="fs-4">SEO</span>
                </a>
                <div class="text-end">
                        {% if user.is_authenticated %}

                        {% else %}

                        <a href="{% url 'account_login' %}"
                                class="btn btn-outline-dark me-2">Login</a>
                        <a href="{% url 'account_signup' %}"
                                class="btn btn-dark">Register</a>
                        {% endif %}
                </div>
        </div>
</header>

app/templates/index.html
{% extends 'base.html' %}


{% block head_title %}
Home
{% endblock head_title %}



{% block content %}
<div class="container my-5">
    <h1 class="fs-1">Welcome to the home page!</h1>
    <hr>

    <div class="container my-5">
        <!-- <div class="row row-cols-1 row-cols-md-3 g-4">
            <a class="text-decoration-none"
                href="{% url 'products:product-list' %}">
                <div class="col">
                    <div class="card text-white bg-secondary mb-3"
                        style="max-width: 18rem;">
                        <div class="card-header">Products</div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">Some quick example text to
                                build on the card title and make up the bulk of
                                the card's content.</p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="text-decoration-none"
                href="{% url 'suppliers:supplier-list' %}">
                <div class="col">
                    <div class="card text-white bg-info mb-3"
                        style="max-width: 18rem;">
                        <div class="card-header">Supplier</div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">Some quick example text to
                                build on the card title and make up the bulk of
                                the card's content.</p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="text-decoration-none"
                href="{% url 'suppliers:supplier-list' %}">
                <div class="col">
                    <div class="card text-white bg-primary mb-3"
                        style="max-width: 18rem;">
                        <div class="card-header">Supplier</div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">Some quick example text to
                                build on the card title and make up the bulk of
                                the card's content.</p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="text-decoration-none"
                href="{% url 'suppliers:supplier-list' %}">
                <div class="col">
                    <div class="card text-white bg-warning mb-3"
                        style="max-width: 18rem;">
                        <div class="card-header">Supplier</div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">Some quick example text to
                                build on the card title and make up the bulk of
                                the card's content.</p>
                        </div>
                    </div>
                </div>
            </a>
            <a class="text-decoration-none"
                href="{% url 'suppliers:supplier-list' %}">
                <div class="col">
                    <div class="card text-white bg-secondary mb-3"
                        style="max-width: 18rem;">
                        <div class="card-header">Supplier</div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">Some quick example text to
                                build on the card title and make up the bulk of
                                the card's content.</p>
                        </div>
                    </div>
                </div>
            </a>
        </div> -->
    </div>
</div>
{% endblock content %}

app/templates/message.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show col-sm-12 col-md-12 col-lg-5 col-xl-3 mb-3  message-timeout"
    style="position: absolute; bottom:2rem; left:2rem; z-index:1000;"
    role="alert">
    {{ message }}
    <button type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<script>
    $(".message-timeout").delay(2500).fadeOut();
</script>

app/templates/pagination.html
<div class="d-flex justify-content-end">

    <div class="pagination small">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

app/templates/sidebar.html
<div class="flex-shrink-0 p-3 vh-100" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold">Menu</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Overview</a></li>
            <li><a href="#" class="link-dark rounded">Updates</a></li>
            <li><a href="#" class="link-dark rounded">Reports</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          Dashboard
        </button>
        <div class="collapse" id="dashboard-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Overview</a></li>
            <li><a href="#" class="link-dark rounded">Weekly</a></li>
            <li><a href="#" class="link-dark rounded">Monthly</a></li>
            <li><a href="#" class="link-dark rounded">Annually</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          Orders
        </button>
        <div class="collapse" id="orders-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">New</a></li>
            <li><a href="#" class="link-dark rounded">Processed</a></li>
            <li><a href="#" class="link-dark rounded">Shipped</a></li>
            <li><a href="#" class="link-dark rounded">Returned</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#inventory-collapse" aria-expanded="false">
          Inventory
        </button>
        <div class="collapse" id="inventory-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'products:product-list' %}" class="link-dark rounded">Stock</a></li>
            <!-- <li><a href="#" class="link-dark rounded">Computers</a></li>
            <li><a href="#" class="link-dark rounded"></a></li>
            <li><a href="#" class="link-dark rounded">Returned</a></li> -->
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">New...</a></li>
            <li><a href="#" class="link-dark rounded">Profile</a></li>
            <li><a href="#" class="link-dark rounded">Settings</a></li>
            <li><a href="#" class="link-dark rounded">Sign out</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>